### ISSUE TITLE
Format numpy.float32 not supported.

### ISSUE THREAD

**Issue by damienpicard** [arnoutaertgeerts/DeSchipjes#2]
The panda dataframes created by ModelicaRes use the format numpy.float32. This lead to an error when used in plot.charts(df). 

If the dataframe is firstly converted to float, no problems occur.

**Comment by arnoutaertgeerts** [comment]
JOENG DIT IS IN TOTAAL DE FOUTE REPOSITORY MAAR IK HEB HET GEMAAKT
